### ISSUE TITLE
socket.connect blocking gulp task from completing

### ISSUE THREAD

**Issue by RongxinZhang** [tj/axon#147]
Hi,

I'm using a logger in my gulp task that uses a yal-server.
However when the task is complete, it is never exitted. 

After digging around. I find that when I comment out socket.connect( ). The task completes.

Is there a way to make axon's socket connection non-blocking?

```
var sock = axon.socket('push')
 sock.format('json')
 sock.connect(addr)
```

**Comment by RongxinZhang** [comment]
@jcrugzz @tj Apologies if I have miss used something completely.

**Comment by jcrugzz** [comment]
Node wont exit if a server is running or a socket is keeping it open. You
have to close it first.

On Wed, Jul 29, 2015 at 3:37 PM, Rongxin Zhang <notifications@github.com>
wrote:

> @jcrugzz <https://github.com/jcrugzz> @tj <https://github.com/tj>
> Apologies if I have miss used something completely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tj/axon/issues/147#issuecomment-126070776>.
>



-- 
Jarrett Cruger
Software Engineer at GoDaddy <https://www.godaddy.com/> Inc.

**Comment by RongxinZhang** [comment]
@jcrugzz thanks
