### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by antitoxic** [tj/axon#158]
Last activity is more than 6 months ago. I'm trying to evaluate zeromq vs axon. 

Axon beneits are the lack of yet-another-server-dependency.

cc @tj

**Comment by tj** [comment]
Not by myself nope, I don't write node anymore. Happy to add anyone who is interested in maintaining

**Comment by antitoxic** [comment]
Thanks for the quick answer. I was just exploring work-related usage. Sadly I can't contribute right now either.
